version: '3.9'


services:
  db:
    image: postgres:14-alpine
    ports:
      - '6543:6543'

    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    volumes:
      - ./data/db:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    volumes:
      - ./frontend:/my-app

    depends_on:
      - db

  # backend: 
  #   build: 
  #     context: ./mvproject
  #     dockerfile: Dockerfile

  #   environment:
  #     - POSTGRES_PASSWORD=admin
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=postgres

  #   ports:
  #     - '8000:8000'

  #   volumes:
  #     - ./backend:/my-app/mvproject

  #   depends_on:
  #     - db