version: '3'

services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: mapping_violence
    volumes:
      - .:/mapping_violence
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: kartoza/postgis:12.1
    environment:
      - POSTGRES_DB=mappingviolence
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
