# Generated by Django 4.1.3 on 2022-11-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=250)),
                ('weapon', models.CharField(max_length=250)),
                ('conviction', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
